import type { JobDefinition } from './jobTypes';

export const JOB_REGISTRY: string[] = [
  'pav_voc_school_teacher',
  'city_office_secretary',
  'city_cafe_waitress',
  'city_hospital_nurse',
  'city_diner_dishwasher',
  'city_diner_floor_washer',
  'city_office_cleaner',
  'city_office_toilet_cleaner',
  'city_diner_secretary',
  'city_strip_bargirl',
  'city_strip_stripper',
  'city_pussycats_clerk',
  'city_market_saleswoman',
  'city_pornstudio_actress',
  'city_pornstudio_delivery',
  'city_aphrodite_model',
  'city_salon_masseuse',
  'pav_hotel_maid',
  'pav_clinic_cleaner',
  'pav_factory',
  'pav_mailgirl',
  'pav_tour_guide',
  'pav_barbershop_cleaner',
  'pav_train_cleaner',
  'pav_pool_lifeguard',
  'highway_brothel_prostitute',
  'nich_maid',
];

export const JOB_DEFINITIONS: Record<string, JobDefinition> = {
  pav_voc_school_teacher: {
    id: 'pav_voc_school_teacher',
    title: 'Teacher',
    location: 'Pavlovsk Lyceum',
    scheduleMode: 'fixed',
    desc: 'Teach classes at the Pavlovsk Lyceum on weekdays. Requires a university diploma. Pay is 150 per teaching hour.',
    hireHints: ['The Pavlovsk Lyceum personnel department is hiring a certified teacher. Requires a university diploma. Monday to Saturday, 14:00-16:00.'],
    cardHidden: true,
    schedules: [{ workDays: '1 2 3 4 5 6', arrival: 840, start: 900, shift: 120 }],
    payInterval: 'none',
    payRate: 0,
    penaltyPerMiss: 0,
    penaltyMaxDebt: 0,
    blocking: false,
    addToCalendar: true,
    showStatIcon: false,
    scheduleSwitchable: false,
    refreshDesc: false,
    createAvailabilityEvents: false,
  },
  city_office_secretary: {
    id: 'city_office_secretary',
    title: 'Office Secretary',
    location: 'Titran-Express',
    scheduleMode: 'fixed',
    desc: 'Manage schedules, handle correspondence, and keep the office running smoothly.',
    hireHints: [
      'Find the job listing for Titran-Express online or at various notice boards.',
      "You've seen the job listing. Visit Titran-Express and ask for an interview. A secretary certificate is required.",
    ],
    cardHidden: true,
    schedules: [{ workDays: '1 2 3 4 5', arrival: 480, start: 540, shift: 480 }],
    payInterval: 'shift',
    payRate: 1500,
    penaltyPerMiss: 0,
    penaltyMaxDebt: 0,
    blocking: true,
    addToCalendar: true,
    showStatIcon: true,
    scheduleSwitchable: false,
    refreshDesc: false,
    createAvailabilityEvents: false,
  },
  city_cafe_waitress: {
    id: 'city_cafe_waitress',
    title: 'Cafe Waitress',
    location: 'the Roadhouse Cafe',
    scheduleMode: 'fixed',
    desc: 'Take orders, serve tables, and keep customers happy. Tips can supplement your wages.',
    hireHints: ['Stop by the Roadhouse Cafe during opening hours and ask about waitress work.'],
    cardHidden: false,
    schedules: [{ workDays: '2 3 4 5 6', arrival: 660, start: 720, shift: 480 }],
    payInterval: 'shift',
    payRate: 600,
    penaltyPerMiss: 0,
    penaltyMaxDebt: 0,
    blocking: true,
    addToCalendar: true,
    showStatIcon: true,
    scheduleSwitchable: false,
    refreshDesc: false,
    createAvailabilityEvents: false,
  },
  city_hospital_nurse: {
    id: 'city_hospital_nurse',
    title: 'Hospital Nurse',
    location: 'City Hospital',
    scheduleMode: 'fixed',
    desc: 'Assist with patient care, take vitals, and support the nursing team.',
    hireHints: ['Kat put in a good word for you at the clinic. Visit the city clinic and ask to see the chief doctor.'],
    cardHidden: true,
    schedules: [{ workDays: '1 2 3 4 5', arrival: 480, start: 540, shift: 420 }],
    payInterval: 'shift',
    payRate: 1500,
    penaltyPerMiss: 0,
    penaltyMaxDebt: 0,
    blocking: true,
    addToCalendar: true,
    showStatIcon: true,
    scheduleSwitchable: false,
    refreshDesc: false,
    createAvailabilityEvents: false,
  },
  city_diner_dishwasher: {
    id: 'city_diner_dishwasher',
    title: 'Diner Cleaning Gig',
    location: 'City Diner',
    scheduleMode: 'windowed',
    desc: 'Wash dishes and keep the kitchen clean. Come by any time during opening hours.',
    hireHints: ['Head into the City Diner kitchen and ask to wash dishes. No experience needed.'],
    cardHidden: false,
    schedules: [{ workDays: '1 2 3 4 5 6 7', arrival: 360, start: 1380, shift: 60 }],
    payInterval: 'shift',
    payRate: 70,
    penaltyPerMiss: 0,
    penaltyMaxDebt: 0,
    blocking: false,
    addToCalendar: false,
    showStatIcon: false,
    scheduleSwitchable: false,
    refreshDesc: false,
    createAvailabilityEvents: false,
  },
  city_diner_floor_washer: {
    id: 'city_diner_floor_washer',
    title: 'Diner Floor Washing',
    location: 'City Diner',
    scheduleMode: 'windowed',
    desc: 'Mop and clean the dining area floor each morning before the rush.',
    hireHints: ["Complete a few dishwashing shifts at the City Diner first, then ask about floor washing too."],
    cardHidden: true,
    schedules: [{ workDays: '1 2 3 4 5 6 7', arrival: 360, start: 600, shift: 60 }],
    payInterval: 'shift',
    payRate: 70,
    penaltyPerMiss: 0,
    penaltyMaxDebt: 0,
    blocking: false,
    addToCalendar: false,
    showStatIcon: false,
    scheduleSwitchable: false,
    refreshDesc: false,
    createAvailabilityEvents: false,
  },
  city_office_cleaner: {
    id: 'city_office_cleaner',
    title: 'Office Cleaning Gig',
    location: 'Small Office Building',
    scheduleMode: 'windowed',
    desc: 'Sweep and mop the floors of the building. Come by any time during business hours.',
    hireHints: [
      "You'll hear about this job by word of mouth. Try chatting with people at the city market.",
      "You've heard about a cleaning job in a small office building. Stop by and ask about available work.",
    ],
    cardHidden: true,
    schedules: [{ workDays: '1 2 3 4 5 6 7', arrival: 420, start: 1320, shift: 60 }],
    payInterval: 'shift',
    payRate: 65,
    penaltyPerMiss: 0,
    penaltyMaxDebt: 0,
    blocking: false,
    addToCalendar: false,
    showStatIcon: false,
    scheduleSwitchable: false,
    refreshDesc: false,
    createAvailabilityEvents: false,
  },
  city_office_toilet_cleaner: {
    id: 'city_office_toilet_cleaner',
    title: 'Toilet Cleaning Gig',
    location: 'Small Office Building',
    scheduleMode: 'windowed',
    desc: 'Clean and maintain the restrooms at the office building.',
    hireHints: [
      "This position opens up after you've spent some time cleaning floors at the office building.",
      'Boris Ivanovich mentioned he needs someone for the restrooms. Ask him about more work at the office.',
    ],
    cardHidden: true,
    schedules: [{ workDays: '1 2 3 4 5 6 7', arrival: 420, start: 1320, shift: 60 }],
    payInterval: 'shift',
    payRate: 65,
    penaltyPerMiss: 0,
    penaltyMaxDebt: 0,
    blocking: false,
    addToCalendar: false,
    showStatIcon: false,
    scheduleSwitchable: false,
    refreshDesc: false,
    createAvailabilityEvents: false,
  },
  city_diner_secretary: {
    id: 'city_diner_secretary',
    title: 'Diner Secretary',
    location: 'City Diner',
    scheduleMode: 'fixed',
    desc: 'Handle office administration and paperwork. Requires a secretary certificate.',
    hireHints: ['Obtain a secretary diploma, then show it to Anatoly Borisovich at the diner when the opportunity arises.'],
    cardHidden: true,
    schedules: [{ workDays: '1 2 3 4 5', arrival: 540, start: 600, shift: 420 }],
    payInterval: 'shift',
    payRate: 1250,
    penaltyPerMiss: 0,
    penaltyMaxDebt: 0,
    blocking: true,
    addToCalendar: true,
    showStatIcon: true,
    scheduleSwitchable: false,
    refreshDesc: false,
    createAvailabilityEvents: false,
  },
  city_strip_bargirl: {
    id: 'city_strip_bargirl',
    title: 'Strip Club Bargirl',
    location: 'Golden Girls',
    scheduleMode: 'fixed',
    desc: 'Serve drinks and tend the bar on fixed evening and night shifts.',
    hireHints: ['Ask at the Golden Girls strip club about bar work during evening opening hours.'],
    cardHidden: false,
    schedules: [
      { workDays: '3 4', arrival: 1020, start: 1080, shift: 540 },
      { workDays: '5 6', arrival: 1020, start: 1080, shift: 540 },
    ],
    payInterval: 'shift',
    payRate: 1125,
    penaltyPerMiss: 0,
    penaltyMaxDebt: 0,
    blocking: true,
    addToCalendar: true,
    showStatIcon: true,
    scheduleSwitchable: true,
    refreshDesc: false,
    createAvailabilityEvents: false,
  },
  city_strip_stripper: {
    id: 'city_strip_stripper',
    title: 'Stripper',
    location: 'Golden Girls',
    scheduleMode: 'booking',
    desc: 'Dance and strip at the Golden Girls club. Sign up for shifts on the backstage whiteboard.',
    hireHints: ["Ask the manager at the Golden Girls strip club about stripper work. You'll need erotic and pole dancing skills to pass the audition."],
    cardHidden: false,
    schedules: [],
    bookingWindowDays: 14,
    bookingSlotsPerDay: 2,
    bookingMaxConcurrent: 0,
    bookingMinGapDays: 0,
    bookingSlots: [
      { arrival: 1020, start: 1080, shift: 300 },
      { arrival: 1230, start: 1260, shift: 360 },
    ],
    payInterval: 'none',
    payRate: 0,
    penaltyPerMiss: 0,
    penaltyMaxDebt: 0,
    blocking: true,
    addToCalendar: true,
    showStatIcon: true,
    scheduleSwitchable: false,
    refreshDesc: false,
    createAvailabilityEvents: false,
  },
  city_pussycats_clerk: {
    id: 'city_pussycats_clerk',
    title: 'Shop Clerk',
    location: 'Pussy-Cats, City Mall',
    scheduleMode: 'fixed',
    desc: "Work the register, fold stock, and help customers find what they're looking for.",
    hireHints: ['Visit the Pussy-Cats clothing store and ask the manager about available clerk positions.'],
    cardHidden: false,
    schedules: [
      { workDays: '1 2 3 4 5', arrival: 930, start: 960, shift: 240 },
      { workDays: '6 7', arrival: 510, start: 540, shift: 360 },
      { workDays: '1 2 3 4 5', arrival: 510, start: 540, shift: 360 },
    ],
    payInterval: 'hourly',
    payRate: 205,
    penaltyPerMiss: 1,
    penaltyMaxDebt: 0,
    blocking: true,
    addToCalendar: true,
    showStatIcon: true,
    scheduleSwitchable: true,
    refreshDesc: false,
    createAvailabilityEvents: false,
  },
  city_market_saleswoman: {
    id: 'city_market_saleswoman',
    title: 'Market Saleswoman',
    location: 'City Market',
    scheduleMode: 'fixed',
    desc: "Sell clothing from Arthur's market stall in the city. Pay is commission-based, settled at end of each shift.",
    hireHints: ['Look for the ad on a stall at the city market. Arthur is hiring a female saleswoman for Tuesday, Thursday and Saturday shifts.'],
    cardHidden: true,
    schedules: [{ workDays: '2 4 6', arrival: 480, start: 540, shift: 300 }],
    payInterval: 'none',
    payRate: 0,
    penaltyPerMiss: 0,
    penaltyMaxDebt: 0,
    blocking: false,
    addToCalendar: true,
    showStatIcon: false,
    scheduleSwitchable: false,
    refreshDesc: false,
    createAvailabilityEvents: false,
  },
  city_pornstudio_actress: {
    id: 'city_pornstudio_actress',
    title: 'Porn Actress',
    location: 'Porn Studio',
    scheduleMode: 'booking',
    desc: 'Film adult movies at the porn studio. Book shoots from the available schedule.',
    hireHints: ["Visit the porn studio in the city's red light district and ask about casting. You'll need to be comfortable showing off your body."],
    cardHidden: true,
    schedules: [],
    bookingWindowDays: 42,
    bookingSlotsPerDay: 4,
    bookingMaxConcurrent: 5,
    bookingMinGapDays: 6,
    bookingSlots: [
      { arrival: 540, start: 600, shift: 240 },
      { arrival: 660, start: 720, shift: 240 },
      { arrival: 780, start: 840, shift: 240 },
      { arrival: 900, start: 960, shift: 240 },
    ],
    payInterval: 'shift',
    payRate: 0,
    penaltyPerMiss: 0,
    penaltyMaxDebt: 20000,
    blocking: true,
    addToCalendar: true,
    showStatIcon: true,
    scheduleSwitchable: false,
    refreshDesc: true,
    createAvailabilityEvents: false,
    onMissHandler: 'pornschedule',
    onMissHandlerFunc: 'on_booking_miss',
  },
  city_pornstudio_delivery: {
    id: 'city_pornstudio_delivery',
    title: 'Delivery Courier',
    location: 'City Porn Studio',
    scheduleMode: 'on_demand',
    desc: 'Make weekly deliveries for the studio. Pick up a drive on Friday, deliver to the sauna, and return with the payment envelope the same day.',
    hireHints: [
      'A contact near the residential trash area may be able to get you this gig.',
      "You've been offered the job. Visit the porn studio and show your passport to Dimitri.",
    ],
    cardHidden: true,
    schedules: [],
    availableDays: '5',
    availableStart: 540,
    availableEnd: 1320,
    payInterval: 'none',
    payRate: 0,
    penaltyPerMiss: 0,
    penaltyMaxDebt: 0,
    blocking: false,
    addToCalendar: false,
    showStatIcon: true,
    scheduleSwitchable: false,
    refreshDesc: false,
    createAvailabilityEvents: true,
  },
  city_aphrodite_model: {
    id: 'city_aphrodite_model',
    title: 'Model',
    location: 'Aphrodite Photography',
    scheduleMode: 'on_demand',
    desc: 'Freelance glamour and erotic modelling for Aphrodite Photography.',
    hireHints: ['Visit the Aphrodite Photography studio in the city center and ask about modelling work.'],
    cardHidden: false,
    schedules: [],
    availableDays: '1 2 3 4 5 6 7',
    availableStart: 420,
    availableEnd: 1260,
    payInterval: 'none',
    payRate: 0,
    penaltyPerMiss: 0,
    penaltyMaxDebt: 0,
    blocking: false,
    addToCalendar: false,
    showStatIcon: true,
    scheduleSwitchable: false,
    refreshDesc: true,
    createAvailabilityEvents: false,
  },
  city_salon_masseuse: {
    id: 'city_salon_masseuse',
    title: 'Masseuse',
    location: 'Beauty Bar Salon',
    scheduleMode: 'booking',
    desc: 'Work as a masseuse at the Beauty Bar salon in the city mall.',
    hireHints: ['Visit the Beauty Bar salon in the city mall and speak to the receptionist about available masseuse positions.'],
    cardHidden: false,
    schedules: [],
    bookingWindowDays: 14,
    bookingSlotsPerDay: 3,
    bookingMaxConcurrent: 21,
    bookingMinGapDays: 0,
    bookingSlots: [
      { arrival: 510, start: 540, shift: 240 },
      { arrival: 750, start: 780, shift: 240 },
      { arrival: 990, start: 1020, shift: 240 },
    ],
    payInterval: 'none',
    payRate: 0,
    penaltyPerMiss: 0,
    penaltyMaxDebt: 0,
    blocking: true,
    addToCalendar: true,
    showStatIcon: true,
    scheduleSwitchable: false,
    refreshDesc: true,
    createAvailabilityEvents: false,
  },
  pav_hotel_maid: {
    id: 'pav_hotel_maid',
    title: 'Hotel Cleaning Gig',
    location: 'Pavlovsk Hotel',
    scheduleMode: 'fixed',
    desc: 'Clean guest rooms and common areas to standard. Tips from guests are common.',
    hireHints: [
      'Check newspaper job listings or online job boards for the hotel maid advertisement.',
      "You've seen a maid-wanted ad at the Pavlovsk Hotel. Ask the receptionist for details.",
      'Speak with the hotel manager — available between 12:00 and 14:00 — to discuss starting as a maid.',
    ],
    cardHidden: true,
    schedules: [{ workDays: '1 2 3 4 5 6 7', arrival: 960, start: 1020, shift: 150 }],
    payInterval: 'shift',
    payRate: 375,
    penaltyPerMiss: 0,
    penaltyMaxDebt: 0,
    blocking: false,
    addToCalendar: true,
    showStatIcon: false,
    scheduleSwitchable: false,
    refreshDesc: false,
    createAvailabilityEvents: false,
  },
  pav_clinic_cleaner: {
    id: 'pav_clinic_cleaner',
    title: 'Clinic Cleaning Gig',
    location: 'Pavlovsk Clinic',
    scheduleMode: 'windowed',
    desc: 'Keep the building spotless during afternoon and evening hours.',
    hireHints: [
      'Head to the Pavlovsk clinic and look for the job listing posted near the entrance.',
      "You've seen the job listing. Ask the head doctor directly — they're available between 14:00 and 21:00.",
    ],
    cardHidden: true,
    schedules: [{ workDays: '1 2 3 4 5 6 7', arrival: 840, start: 1260, shift: 60 }],
    payInterval: 'shift',
    payRate: 100,
    penaltyPerMiss: 0,
    penaltyMaxDebt: 0,
    blocking: false,
    addToCalendar: false,
    showStatIcon: false,
    scheduleSwitchable: false,
    refreshDesc: false,
    createAvailabilityEvents: false,
  },
  pav_factory: {
    id: 'pav_factory',
    title: 'Factory Worker',
    location: 'Pavlovsk Factory',
    scheduleMode: 'fixed',
    desc: 'Sew garments on the production line. Mandatory weekday shifts.',
    hireHints: ['Apply at the Pavlovsk textile factory during working hours.'],
    cardHidden: false,
    schedules: [
      { workDays: '1 2 3 4 5', arrival: 900, start: 960, shift: 240 },
      { workDays: '1 2 3 4 5', arrival: 420, start: 480, shift: 480 },
    ],
    payInterval: 'hourly',
    payRate: 150,
    penaltyPerMiss: 1,
    penaltyMaxDebt: 3,
    blocking: true,
    addToCalendar: true,
    showStatIcon: true,
    scheduleSwitchable: true,
    refreshDesc: false,
    createAvailabilityEvents: false,
  },
  pav_mailgirl: {
    id: 'pav_mailgirl',
    title: 'Mail Delivery Gig',
    location: 'Pavlovsk Post Office',
    scheduleMode: 'fixed',
    desc: "Carry and deliver the town's mail on your assigned routes.",
    hireHints: [
      'Ask the postmaster at the Pavlovsk post office about mail delivery work on Saturdays.',
      "You turned down the Saturday delivery offer. Head back to the post office if you've changed your mind.",
      'The postmaster is expecting you at the post office on Saturday between 11:00 and 12:00 for a trial shift.',
      "You completed your trial shift. Go back to the post office and tell the postmaster you'd like the regular Saturday job.",
    ],
    cardHidden: false,
    schedules: [{ workDays: '6', arrival: 660, start: 720, shift: 180 }],
    payInterval: 'shift',
    payRate: 450,
    penaltyPerMiss: 1,
    penaltyMaxDebt: 4,
    blocking: false,
    addToCalendar: true,
    showStatIcon: true,
    scheduleSwitchable: false,
    refreshDesc: false,
    createAvailabilityEvents: false,
  },
  pav_tour_guide: {
    id: 'pav_tour_guide',
    title: 'Tour Guide Gig',
    location: 'Pavlovsk Park',
    scheduleMode: 'windowed',
    desc: 'Escort tourists around the park and share its history. Summer only.',
    hireHints: ['Ask about tour guide positions at the Pavlovsk Park entrance. Only available in summer.'],
    cardHidden: false,
    schedules: [{ workDays: '1 2 3 4 5 6 7', arrival: 480, start: 720, shift: 480 }],
    workDates: '0601-0831',
    payInterval: 'shift',
    payRate: 1000,
    penaltyPerMiss: 0,
    penaltyMaxDebt: 0,
    blocking: false,
    addToCalendar: true,
    showStatIcon: false,
    scheduleSwitchable: false,
    refreshDesc: false,
    createAvailabilityEvents: false,
  },
  pav_barbershop_cleaner: {
    id: 'pav_barbershop_cleaner',
    title: 'Barbershop Cleaning Gig',
    location: 'Pavlovsk Barbershop',
    scheduleMode: 'windowed',
    desc: 'Sweep up hair and keep the place tidy. Come by any time the shop is open.',
    hireHints: ["Visit the Pavlovsk barbershop and ask Mr. Syomin if he needs help keeping the place clean."],
    cardHidden: false,
    schedules: [{ workDays: '1 2 3 4 5 6 7', arrival: 480, start: 1080, shift: 60 }],
    payInterval: 'shift',
    payRate: 125,
    penaltyPerMiss: 0,
    penaltyMaxDebt: 0,
    blocking: false,
    addToCalendar: false,
    showStatIcon: false,
    scheduleSwitchable: false,
    refreshDesc: false,
    createAvailabilityEvents: false,
  },
  pav_train_cleaner: {
    id: 'pav_train_cleaner',
    title: 'Train Station Cleaning Gig',
    location: 'Pavlovsk Train Station',
    scheduleMode: 'on_demand',
    desc: 'Clean the train station waiting room and restrooms. Work any time you like.',
    hireHints: ["Visit the station manager's office at the Pavlovsk railway station between 08:00 and 17:00 and ask about the cleaning job."],
    cardHidden: false,
    schedules: [],
    availableDays: '1 2 3 4 5 6 7',
    availableStart: 0,
    availableEnd: 1439,
    payInterval: 'shift',
    payRate: 250,
    penaltyPerMiss: 0,
    penaltyMaxDebt: 0,
    blocking: false,
    addToCalendar: false,
    showStatIcon: false,
    scheduleSwitchable: false,
    refreshDesc: false,
    createAvailabilityEvents: false,
  },
  pav_pool_lifeguard: {
    id: 'pav_pool_lifeguard',
    title: 'Lifeguard',
    location: 'Pavlovsk Swimming Pool',
    scheduleMode: 'fixed',
    desc: 'Watch over swimmers and keep the pool safe. Weekend shifts at the Pavlovsk pool.',
    hireHints: [
      'Look for the lifeguard-wanted sign at the Pavlovsk swimming pool entrance. Available in summer.',
      "You've applied for the lifeguard position. Training begins next Saturday morning between 8:00 and 9:00.",
      "You've completed your first training day. Come back Sunday morning between 8:00 and 9:00 to finish training.",
    ],
    cardHidden: true,
    schedules: [
      { workDays: '6 7', arrival: 660, start: 780, shift: 360 },
      { workDays: '4 5 6 7', arrival: 660, start: 780, shift: 360 },
    ],
    payInterval: 'shift',
    payRate: 250,
    penaltyPerMiss: 0,
    penaltyMaxDebt: 0,
    blocking: false,
    addToCalendar: true,
    showStatIcon: false,
    scheduleSwitchable: true,
    refreshDesc: false,
    createAvailabilityEvents: false,
  },
  highway_brothel_prostitute: {
    id: 'highway_brothel_prostitute',
    title: 'Highway Brothel Prostitute',
    location: 'Pavlovsk Highway Brothel',
    scheduleMode: 'on_demand',
    desc: "Work as a prostitute at the highway S&M brothel. On-demand shifts.",
    hireHints: ['Get wasted in the highway hotel bar and see where life takes you.'],
    cardHidden: true,
    schedules: [],
    availableDays: '1 2 3 4 5 6 7',
    availableStart: 0,
    availableEnd: 1439,
    payInterval: 'hourly',
    payRate: 500,
    penaltyPerMiss: 0,
    penaltyMaxDebt: 0,
    blocking: false,
    addToCalendar: false,
    showStatIcon: false,
    scheduleSwitchable: false,
    refreshDesc: false,
    createAvailabilityEvents: false,
  },
  nich_maid: {
    id: 'nich_maid',
    title: 'Live-in Maid',
    location: "Nicholas' Apartment",
    scheduleMode: 'fixed',
    desc: 'Cook, clean, and manage the household. Salary paid monthly via letter.',
    hireHints: [
      'Build a close friendship with Tanya — she may know of an opportunity.',
      'Tanya wants to set up a job interview with her parents. Get a maid uniform and visit their apartment dressed the part.',
    ],
    cardHidden: true,
    schedules: [{ workDays: '4 5 6 7 1 2', arrival: 480, start: 540, shift: 480 }],
    payInterval: 'none',
    payRate: 0,
    penaltyPerMiss: 0,
    penaltyMaxDebt: 0,
    blocking: true,
    addToCalendar: true,
    showStatIcon: true,
    scheduleSwitchable: false,
    refreshDesc: false,
    createAvailabilityEvents: false,
  },
  pav_leonid_slave: {
    id: 'pav_leonid_slave',
    title: 'Slave',
    location: "Leonid's Office",
    scheduleMode: 'booking',
    desc: 'You are obligated to present yourself to Leonid Nosov at his office when summoned.',
    hireHints: [],
    cardHidden: false,
    schedules: [],
    bookingWindowDays: 7,
    bookingSlotsPerDay: 1,
    bookingMaxConcurrent: 7,
    bookingMinGapDays: 0,
    bookingSlots: [{ arrival: 1140, start: 1200, shift: 120 }],
    payInterval: 'none',
    payRate: 0,
    penaltyPerMiss: 0,
    penaltyMaxDebt: 0,
    blocking: false,
    addToCalendar: true,
    showStatIcon: true,
    scheduleSwitchable: false,
    refreshDesc: false,
    createAvailabilityEvents: false,
    onMissHandler: 'leonid',
    onMissHandlerFunc: 'on_miss',
  },
};
