// AUTO-GENERATED FILE — DO NOT EDIT, fix the transpiler (scripts/qsp-transpile)
import type { GameState, ActionDef, LocationDef } from '../../core/types';
import type { SceneBuilder } from '../../core/scene';

function enter(s: GameState, scene: SceneBuilder): void {
  (s as any).santehnikgr = 'gt \'kit_din\', \'santehnikgr\'';
  (s as any).santehnikend = 'gt \'kit_din\', \'santehnikend\'';
  (s as any).santehnikend1 = 'gt \'kit_din\', \'santehnikend1\'';
  (s as any).santehnikend2 = 'gt \'kit_din\', \'santehnikend2\'';
  (s as any).santehnikend3 = 'gt \'kit_din\', \'santehnikend3\'';
  (s as any).santehnik1 = 'gs \'kit_din\', \'santehnik1\'';
  (s as any).santehnik = 'gt \'kit_din\', \'santehnik\'';
  (s as any).dirtarm = 'gs \'kit_din\', \'dirtarm\'';
  (s as any).edagotd = 'gt \'kit_din\', \'edagotd\'';
  (s as any).edagotpk = 'gt \'kit_din\', \'edagotpk\'';
  (s as any).edahotd = 'gt \'kit_din\', \'edahotd\'';
  (s as any).eatout = 'gt \'kit_din\', \'eatout\'';
  (s as any).posudomashina = 'gs \'kit_din\', \'posudomashina\'';
  (s as any).edasnack = 'gs \'kit_din\', \'edasnack\'';
  (s as any).pranik = 'gs \'kit_din\', \'pranik\'';
  (s as any).dritea = 'gs \'kit_din\', \'dritea\'';
  (s as any).edaD = 'gs \'kit_din\', \'edaD\'';
  (s as any).fatdel = 'gs \'kit_din\', \'fatdel\'';
  (s as any).driwater = 'gs \'kit_din\', \'driwater\'';
  (s as any).fill_bottle = 'gs \'kit_din\', \'fill_bottle\'';
  (s as any).sandwich = 'gs \'kit_din\', \'sandwich\'';
  (s as any).lekarstvo = 'gs \'kit_din\', \'lekarstvo\'';
  (s as any).vitamin = 'gs \'kit_din\', \'vitamin\'';
  (s as any).mobile_check = 'gs \'din_bad\', \'mobile_check\'';
  (s as any).d_salf = 'gt \'din_bad\', \'d_salf\'';
  (s as any).d_mouthwash = 'gt \'din_bad\', \'d_mouthwash\'';
  (s as any).d_bag = 'gt \'din_bad\', \'d_bag\'';
  (s as any).dinalkowin1 = 'gt \'din_bad\', \'dinalkowin1\'';
  (s as any).dinalkowin2 = 'gt \'din_bad\', \'dinalkowin2\'';
  (s as any).din_Switch_Condom_Menu = 'gt \'din_bad\', \'din_Switch_Condom_Menu\'';
  (s as any).din_Table_Condom_Menu = 'gt \'din_bad\', \'din_Table_Condom_Menu\'';
  (s as any).din_Do_Condom_Counts = 'gt \'din_bad\', \'din_Do_Condom_Counts\'';
  (s as any).din_Update_Condom_Counts = 'gt \'din_bad\', \'din_Update_Condom_Counts\'';
  (s as any).d_tabletkied = 'gt \'din_bad\', \'d_tabletkied\'';
  (s as any).d_tabletkiedt = 'gt \'din_bad\', \'d_tabletkiedt\'';
  (s as any).d_tabletkieda = 'gs \'din_bad\', \'d_tabletkieda\'';
  (s as any).d_cycreport_choice = 'gt \'din_bad\', \'d_cycreport_choice\'';
  (s as any).d_cycreport_actor = 'gs \'din_bad\', \'d_cycreport_actor\'';
  (s as any).d_cycreport_upduedate = 'gs \'din_bad\', \'d_cycreport_upduedate\'';
  (s as any).d_pregmovement = 'gs \'din_bad\', \'d_pregmovement\'';
  (s as any).use_steroids = 'gs \'din_bad\', \'use_steroids\'';
  (s as any).use_bcream = 'gs \'din_bad\', \'use_bcream\'';
  (s as any).showerdin = 'gs \'din_van\', \'showerdin\'';
  (s as any).bteeth = 'gs \'din_van\', \'bteeth\'';
  (s as any).dryOff = 'gs \'din_van\', \'dryOff\'';
  (s as any).shower = 'gs \'din_van\', \'shower\'';
  (s as any).bath = 'gs \'din_van\', \'bath\'';
  (s as any).SkinCare = 'gs \'din_van\', \'SkinCare\'';
  (s as any).brit = 'gs \'din_van\', \'brit\'';
  (s as any).tampon = 'gs \'din_van\', \'tampon\'';
  (s as any).quickwash = 'gs \'din_van\', \'quickwash\'';
  (s as any).wearpan = 'gs \'din_van\', \'wearpan\'';
  (s as any).removepan = 'gs \'din_van\', \'removepan\'';
  (s as any).publicpan = 'gs \'din_van\', \'publicpan\'';
  (s as any).basin = 'gs \'din_van\', \'basin\'';
  (s as any).pirManage = 'gs \'din_van\', \'pirManage\'';
  (s as any).enema = 'gs \'din_van\', \'enema\'';
  (s as any).toymanage = 'gs \'din_van\', \'toymanage\'';
  (s as any).palelady = 'gs \'din_van\', \'palelady\'';
  (s as any).brodila = 'gt \'dina\', \'brodila\'';
  (s as any).brodilr = 'gt \'dina\', \'brodilr\'';
  (s as any).brodilk = 'gt \'dina\', \'brodilk\'';
  (s as any).brodils = 'gt \'dina\', \'brodils\'';
  (s as any).dogpot = 'gs \'dina\', \'dogpot\'';
  (s as any).rexpot = 'gs \'dina\', \'rexpot\'';
  (s as any).hypnoDaychange = 'gs \'dina\', \'hypnoDaychange\'';
  (s as any).hypnoAddiction = 'gs \'dina\', \'hypnoAddiction\'';
  (s as any).prezik = 'gs \'dina\', \'prezik\'';
  (s as any).ferteggfather = 'gs \'dina\', \'ferteggfather\'';
  ((s as any).d_mother = (s as any).d_mother ?? {})[1] = 'gs \'dinmother\', \'d_mother[1]\'';
  ((s as any).d_mother = (s as any).d_mother ?? {})[2] = 'gs \'dinmother\', \'d_mother[2]\'';
  ((s as any).d_mother = (s as any).d_mother ?? {})[3] = 'gs \'dinmother\', \'d_mother[3]\'';
  ((s as any).d_mother = (s as any).d_mother ?? {})[4] = 'gs \'dinmother\', \'d_mother[4]\'';
  ((s as any).d_mother = (s as any).d_mother ?? {})[5] = 'gs \'dinmother\', \'d_mother[5]\'';
  ((s as any).d_mother = (s as any).d_mother ?? {})[6] = 'gs \'dinmother\', \'d_mother[6]\'';
  ((s as any).d_mother = (s as any).d_mother ?? {})[7] = 'gs \'dinmother\', \'d_mother[7]\'';
  ((s as any).d_mother = (s as any).d_mother ?? {})[8] = 'gs \'dinmother\', \'d_mother[8]\'';
  (s as any).din_predlog_dima_bj = 'gs \'dinnpc\', \'din_predlog_dima_bj\'';
  (s as any).din_dima_predlog = 'gs \'dinnpc\', \'din_dima_predlog\'';
  (s as any).d_park_placer_bj = 'gs \'skverdin\', \'d_park_placer_bj\'';
  (s as any).d_pp_hand = 'gs \'skverdin\', \'d_pp_hand\'';
  (s as any).d_pp_hjcum = 'gs \'skverdin\', \'d_pp_hjcum\'';
  (s as any).d_pp_squat = 'gs \'skverdin\', \'d_pp_squat\'';
  (s as any).d_pp_bj = 'gs \'skverdin\', \'d_pp_bj\'';
  (s as any).d_pp_bjcum = 'gs \'skverdin\', \'d_pp_bjcum\'';
  (s as any).d_pp_sex = 'gs \'skverdin\', \'d_pp_sex\'';
  (s as any).d_pp_double = 'gs \'skverdin\', \'d_pp_double\'';
  (s as any).d_pp_goend = 'gs \'skverdin\', \'d_pp_goend\'';
  (s as any).din_dush = 'gs \'placer_sex\', \'din_dush\'';
  (s as any).din_analPlugIn_off = 'gs \'placer_sex\', \'din_analPlugIn_off\'';
  (s as any).d_strapon_vag = 'gs \'dinSex2\', \'d_strapon_vag\'';
  (s as any).d_vag_sex_bottle = 'gs \'dinSex2\', \'d_vag_sex_bottle\'';
  (s as any).d_strapon_anal = 'gs \'dinSex2\', \'d_strapon_anal\'';
  (s as any).d_analsex_bottle = 'gs \'dinSex2\', \'d_analsex_bottle\'';
  (s as any).doublepenetration = 'gs \'dinSex2\', \'doublepenetration\'';
  scene.build();
}

export const setup_dynamics: LocationDef = {
  name: 'setup_dynamics',
  region: 'other',
  enter: enter,
};
